# PostgreSQL. Versions 12.0 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mangaverse_development
  username: <%= ENV.fetch("DB_USERNAME", "usuario") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

test:
  <<: *default
  database: mangaverse_test
  username: <%= ENV.fetch("DB_USERNAME", "usuario") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
